name: Sync forks

on:
  schedule:
     - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:


  sync-forks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:

          # Test fork
          - fork: acuD1/test-fork
            main: dev-easyshares/test-fork
            branch: main

          # The calling action: github-forks-sync-action
          - fork: acuD1/github-forks-sync-action
            main: TobKed/github-forks-sync-action
            branch: master

    steps:

      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.DEV }}
          upstream_repository: ${{ matrix.main }}
          target_repository: ${{ matrix.fork }}
          upstream_branch: ${{ matrix.branch }}
          target_branch: sync-fork
          force: true
          tags: true
