name: Sync forks

on:
  schedule:
     - cron: '0 1 * * *'
  workflow_dispatch:

jobs:


  sync-forks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:

          # Test fork

          - fork: acuD1/test-fork
            main: dev-easyshares/test-fork
            branch: main

          # The calling action: github-forks-sync-action

          - fork: acuD1/github-forks-sync-action
            main: TobKed/github-forks-sync-action
            branch: master

          # action

          - fork: acuD1/checkout
            main: actions/checkout
            branch: main

          - fork: acuD1/download-artifact
            main: actions/download-artifact
            branch: main

          - fork: acuD1/download-artifact
            main: actions/download-artifact
            branch: main

          - fork: acuD1/upload-artifact
            main: actions/upload-artifact
            branch: main

          - fork: acuD1/github-script
            main: actions/github-script
            branch: main

          # octokit

          - fork: acuD1/graphql-action
            main: octokit/graphql-action
            branch: main

          # docker

          - fork: acuD1/setup-qemu-action
            main: docker/setup-qemu-action
            branch: master

          - fork: acuD1/setup-buildx-action
            main: docker/setup-buildx-action
            branch: master

          - fork: acuD1/login-action
            main: docker/login-action
            branch: master

          - fork: acuD1/build-push-action
            main: docker/build-push-action
            branch: master

          - fork: acuD1/metadata-action
            main: docker/metadata-action
            branch: master

          # public

          - fork: acuD1/actions-docker-registry-tag
            main: shrink/actions-docker-registry-tag
            branch: main

          - fork: acuD1/action-create-tag
            main:  rickstaa/action-create-tag
            branch: main

          - fork: acuD1/release-action
            main: ncipollo/release-action
            branch: main

          - fork: acuD1/delete-workflow-runs
            main: Mattraks/delete-workflow-runs
            branch: main

    steps:

      - uses: acuD1/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.DEV }}
          upstream_repository: ${{ matrix.main }}
          target_repository: ${{ matrix.fork }}
          upstream_branch: ${{ matrix.branch }}
          target_branch: sync-fork
          force: true
          tags: true
